### ISSUE TITLE
Blocks are not placed but everything else seems to work

### ISSUE THREAD

**Issue by JavierPAYTEF** [Elemend/Builders-Wand#10]
Everything seems to be working fine, except when I right click it doesn't place the blocks. Chat message works and particles are shown.
The minecraft is modded so maybe it's interacting with some mod or something, is there a way for me to check why it's not working?

Also, I've seen this issue #5, and that's happening for me as well. It would be good that unlocking the recipe doesn't give you the item, only crafting it.

**Comment by Elemend** [comment]
Maybe you have the mod "immersive portals" installed? Someone else opened an Issue and that mod made a conflict. If it's not that, propably another mod conflict. I wouldn't know what to do about it.

And when you say:
> It would be good that unlocking the recipe doesn't give you the item, only crafting it.

Sure it would, but the two are connected because unlocking the recipe is something you can detect with an advencement. Crafting the item is not. That's why it is so.

**Comment by JavierPAYTEF** [comment]
Is there a way for me to see if it's throwing an error or something? Would it throw it on the server?
